/* Automatically generated by po2tbl.sed from gnome-breakout.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"GNOME Breakout", 2},
  {"Score: 0", 3},
  {"Lives: 0", 4},
  {"No: %d", 5},
  {"Name: %s", 6},
  {"Author: %s", 7},
  {"Levelfile: %s", 8},
  {"Name:", 9},
  {"Author:", 10},
  {"Filename:", 11},
  {"Score: %d", 12},
  {"Lives: %d", 13},
  {"_Kill ball", 14},
  {"Kill the current ball if it gets stuck", 15},
  {"GNOME Breakout: You win!", 16},
  {"GNOME Breakout: You lose!", 17},
  {"No:", 18},
  {"Levelfile:", 19},
  {"\
The classic arcade game Breakout. Written for my cat, Marmalade. (Hi, Jason! \
Hi, Matt! Hi, JV! Hi, Joe! Hi, Tom! Hi, Richard!)\n\
 \n\
This, if you haven't guessed yet, is a development release. Send bugreports \
and comments to alcaron@senet.com.au, but check to see if they haven't \
already been listed in TODO or BUGS.\n\
 \n\
Also, I've noticed a couple of segfaults that seem to happen randomly, and \
I'm having trouble reproducing them. So run this under gdb, and if it dies, \
send me the backtrace.", 20},
  {"Copyright (c) 2000 Michael Pearson", 21},
  {"Help hasn't been implimented yet. So go ahead and write some for me :)", 22},
  {"GNOME Breakout: Scores", 23},
  {"GNOME Breakout Preferences", 24},
  {"Game", 25},
  {"Levels", 26},
  {"\
Levels cannot be added or removed\n\
while the game is running.", 27},
  {"Add", 28},
  {"Remove", 29},
  {"Difficulty", 30},
  {"Difficulty (next game)", 31},
  {"Easy", 32},
  {"Medium", 33},
  {"Hard", 34},
  {"Automatic Pause", 35},
  {"When we lose keyboard focus", 36},
  {"When the mouse pointer leaves the play window", 37},
  {"When the preferences dialog is active", 38},
  {"Hide the pointer", 39},
  {"Bounce Entropy (Experimental): ", 40},
  {"Control", 41},
  {"Method", 42},
  {"Keyboard", 43},
  {"Mouse", 44},
  {"Bat speed: ", 45},
  {"Keybindings", 46},
  {"Left:", 47},
  {"Right:", 48},
  {"Fire One:", 49},
  {"Fire Two:", 50},
  {"Difficulty in config files is an incorrect value, resetting to defaults", 51},
  {"\
Both keyboard control and mouse control are TRUE in user preferences, \
resetting to defaults", 52},
  {"\
Neither keyboard control or mouse control are TRUE in user preferences, \
resetting to defaults", 53},
  {"Bat speed is lower than allowed range, setting to lowest", 54},
  {"Bat speed is higher than allowed range, setting to highest", 55},
  {"Bounce entropy is lower than allowed range, setting to lowest", 56},
  {"Bounce entropy is higher than allowed range, setting to highest", 57},
};

int _msg_tbl_length = 57;
